# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.srcs/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_1_axi_smc_0.xci
# IP: The module: 'bd_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/bd_fb76.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_0/bd_fb76_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_1/bd_fb76_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_2/bd_fb76_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_3/bd_fb76_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_4/bd_fb76_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_5/bd_fb76_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_6/bd_fb76_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_7/bd_fb76_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_8/bd_fb76_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_9/bd_fb76_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_10/bd_fb76_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_11/bd_fb76_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_12/bd_fb76_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_13/bd_fb76_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_14/bd_fb76_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_15/bd_fb76_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_16/bd_fb76_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_17/bd_fb76_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_18/bd_fb76_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_19/bd_fb76_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_20/bd_fb76_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_21/bd_fb76_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_22/bd_fb76_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_23/bd_fb76_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_24/bd_fb76_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_25/bd_fb76_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_26/bd_fb76_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_27/bd_fb76_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_28/bd_fb76_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_29/bd_fb76_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_30/bd_fb76_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_31/bd_fb76_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_32/bd_fb76_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_33/bd_fb76_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_34/bd_fb76_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_35/bd_fb76_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_36/bd_fb76_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_37/bd_fb76_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_38/bd_fb76_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_39/bd_fb76_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_40/bd_fb76_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_41/bd_fb76_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_42/bd_fb76_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_43/bd_fb76_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_44/bd_fb76_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_45/bd_fb76_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_46/bd_fb76_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_1/bd_fb76_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_1/bd_fb76_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_2/bd_fb76_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_2/bd_fb76_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_3/bd_fb76_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_3/bd_fb76_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_4/bd_fb76_arsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_5/bd_fb76_rsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_6/bd_fb76_awsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_7/bd_fb76_wsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_8/bd_fb76_bsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_12/bd_fb76_s00a2s_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_13/bd_fb76_sarn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_14/bd_fb76_srn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_15/bd_fb76_sawn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_16/bd_fb76_swn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_17/bd_fb76_sbn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_21/bd_fb76_s01a2s_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_22/bd_fb76_sarn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_23/bd_fb76_srn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_27/bd_fb76_s02a2s_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_28/bd_fb76_sarn_2_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_29/bd_fb76_srn_2_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_30/bd_fb76_sawn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_31/bd_fb76_swn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_32/bd_fb76_sbn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_33/bd_fb76_m00s2a_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_34/bd_fb76_m00arn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_35/bd_fb76_m00rn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_36/bd_fb76_m00awn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_37/bd_fb76_m00wn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_38/bd_fb76_m00bn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_40/bd_fb76_m01s2a_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_41/bd_fb76_m01arn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_42/bd_fb76_m01rn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_43/bd_fb76_m01awn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_44/bd_fb76_m01wn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_45/bd_fb76_m01bn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.srcs/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_1_axi_smc_0.xci
# IP: The module: 'bd_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/bd_fb76.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_0/bd_fb76_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_1/bd_fb76_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_2/bd_fb76_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_3/bd_fb76_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_4/bd_fb76_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_5/bd_fb76_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_6/bd_fb76_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_7/bd_fb76_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_8/bd_fb76_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_9/bd_fb76_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_10/bd_fb76_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_11/bd_fb76_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_12/bd_fb76_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_13/bd_fb76_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_14/bd_fb76_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_15/bd_fb76_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_16/bd_fb76_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_17/bd_fb76_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_18/bd_fb76_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_19/bd_fb76_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_20/bd_fb76_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_21/bd_fb76_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_22/bd_fb76_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_23/bd_fb76_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_24/bd_fb76_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_25/bd_fb76_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_26/bd_fb76_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_27/bd_fb76_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_28/bd_fb76_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_29/bd_fb76_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_30/bd_fb76_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_31/bd_fb76_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_32/bd_fb76_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_33/bd_fb76_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_34/bd_fb76_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_35/bd_fb76_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_36/bd_fb76_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_37/bd_fb76_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_38/bd_fb76_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_39/bd_fb76_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_40/bd_fb76_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_41/bd_fb76_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_42/bd_fb76_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_43/bd_fb76_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_44/bd_fb76_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_45/bd_fb76_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_46/bd_fb76_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_1/bd_fb76_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_1/bd_fb76_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_2/bd_fb76_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_2/bd_fb76_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_3/bd_fb76_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_3/bd_fb76_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_4/bd_fb76_arsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_5/bd_fb76_rsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_6/bd_fb76_awsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_7/bd_fb76_wsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_8/bd_fb76_bsw_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_12/bd_fb76_s00a2s_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_13/bd_fb76_sarn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_14/bd_fb76_srn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_15/bd_fb76_sawn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_16/bd_fb76_swn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_17/bd_fb76_sbn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_21/bd_fb76_s01a2s_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_22/bd_fb76_sarn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_23/bd_fb76_srn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_27/bd_fb76_s02a2s_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_28/bd_fb76_sarn_2_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_29/bd_fb76_srn_2_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_30/bd_fb76_sawn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_31/bd_fb76_swn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_32/bd_fb76_sbn_1_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_33/bd_fb76_m00s2a_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_34/bd_fb76_m00arn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_35/bd_fb76_m00rn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_36/bd_fb76_m00awn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_37/bd_fb76_m00wn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_38/bd_fb76_m00bn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_40/bd_fb76_m01s2a_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_41/bd_fb76_m01arn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_42/bd_fb76_m01rn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_43/bd_fb76_m01awn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_44/bd_fb76_m01wn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/bd_0/ip/ip_45/bd_fb76_m01bn_0_ooc.xdc

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd_1/ip/bd_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
