# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.srcs/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/bd_hdmi_text_controller_0_1.xci
# IP: The module: 'bd_hdmi_text_controller_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.srcs/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/bd_hdmi_text_controller_0_1.xci
# IP: The module: 'bd_hdmi_text_controller_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd/ip/bd_hdmi_text_controller_0_1/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet
