# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/constraints/Urbana.xdc

# Block Designs: bd/bd/bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_smc_0/bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_smc_0 || ORIG_REF_NAME==bd_axi_smc_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_uartlite_0_0/bd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_uartlite_0_0 || ORIG_REF_NAME==bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_clk_wiz_1_0/bd_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_clk_wiz_1_0 || ORIG_REF_NAME==bd_clk_wiz_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_mdm_1_0/bd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mdm_1_0 || ORIG_REF_NAME==bd_mdm_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_microblaze_0_0/bd_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_microblaze_0_0 || ORIG_REF_NAME==bd_microblaze_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_bram_if_cntlr_0/bd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dlmb_v10_0/bd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dlmb_v10_0 || ORIG_REF_NAME==bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_bram_if_cntlr_0/bd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bd/ip/bd_ilmb_v10_0/bd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ilmb_v10_0 || ORIG_REF_NAME==bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/bd/ip/bd_lmb_bram_0/bd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_lmb_bram_0 || ORIG_REF_NAME==bd_lmb_bram_0} -quiet] -quiet

# IP: bd/bd/ip/bd_mig_7series_0_0/bd_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_mig_7series_0_0 || ORIG_REF_NAME==bd_mig_7series_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_clk_wiz_1_100M_0/bd_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==bd_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_rst_mig_7series_0_166M_0/bd_rst_mig_7series_0_166M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_rst_mig_7series_0_166M_0 || ORIG_REF_NAME==bd_rst_mig_7series_0_166M_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_ethernetlite_0_0/bd_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_ethernetlite_0_0 || ORIG_REF_NAME==bd_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_intc_0_0/bd_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_intc_0_0 || ORIG_REF_NAME==bd_axi_intc_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_xlconcat_0_0/bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_xlconcat_0_0 || ORIG_REF_NAME==bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_timer_0_0/bd_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_timer_0_0 || ORIG_REF_NAME==bd_axi_timer_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_util_mii_to_rmii_0_0/bd_util_mii_to_rmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_util_mii_to_rmii_0_0 || ORIG_REF_NAME==bd_util_mii_to_rmii_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_0_0/bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_0_0 || ORIG_REF_NAME==bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_1_0/bd_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_1_0 || ORIG_REF_NAME==bd_axi_gpio_1_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_quad_spi_0_0/bd_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_quad_spi_0_0 || ORIG_REF_NAME==bd_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_axi_gpio_2_0/bd_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_axi_gpio_2_0 || ORIG_REF_NAME==bd_axi_gpio_2_0} -quiet] -quiet

# IP: bd/bd/ip/bd_hdmi_text_controller_0_1/bd_hdmi_text_controller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_hdmi_text_controller_0_1 || ORIG_REF_NAME==bd_hdmi_text_controller_0_1} -quiet] -quiet

# XDC: c:/Users/aadit/Documents/ECE_385/385group/Final_proj/final_proj_new/hw/hw.gen/sources_1/bd/bd/bd_ooc.xdc
